---
- name: submit beaker job
  command: bkr job-submit "{{ role_path }}/files/beaker-job-aarch64.xml"
  register: job_result

- name: got job id
  set_fact:
    job_id: "{{ job_result.stdout.split(\"'\")[1] }}"

- name: write instance name info to inventory file
  ini_file:
    path: "{{ playbook_dir }}/inventory"
    section: cloud:vars
    option: job_id
    value: "{{ job_id }}"
    no_extra_spaces: yes

# wait for 2 hours to get a aarch64 machine
- name: wait for beaker server deployment complete
  command: bkr job-results --prettyxml {{ job_id }}
  register: job_finished
  retries: 120
  delay: 60
  until: "'result=\"Pass\" status=\"Running\"' in job_finished.stdout_lines[1]"

- debug:
    var: job_finished

- name: write job-results output to xml file
  copy:
    content: "{{ job_finished.stdout }}"
    dest: job-result-output.xml

- name: get hostname from job-results output
  xml:
    path: job-result-output.xml
    xpath: /job/recipeSet/recipe
    content: attribute
  register: recipe_attribute

- name: set hostname of ostree client
  set_fact:
    beaker_hostname: "{{ recipe_attribute.matches[0].recipe.system }}"

- name: wait for ssh is reachable
  wait_for:
    host: "{{ beaker_hostname }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
    timeout: 3600

- name: add beaker domain name into host group builder
  add_host:
    name: "{{ beaker_hostname }}"
    groups: builder

- name: set private key permisson to 600
  file:
    path: "{{ playbook_dir }}/key/identity"
    mode: "0600"
